#!/usr/bin/env python3
import os,sys
import argparse

#setup argparser to display help if no arguments
class MyParser(argparse.ArgumentParser):
    def error(self, message):
        sys.stderr.write('error: %s\n' % message)
        self.print_help()
        sys.exit(2)

#determine command line arguments and get path
parser = MyParser(description='Plasmadazz - A tool for identifying and annotating plasmids from finished genome assemblies')

parser.add_argument('contigs', type=str,help="fasta file holding the assembly contigs")
parser.add_argument('--db',metavar='database', nargs='+',help="databases used for plasmid id",default="default_database")
parser.add_argument('--rotate',metavar='contig1', nargs='+',help="rotate selected plasmids if an Origin is found")
parser.add_argument('--num-hits',metavar='<int>',help="Number of top hits to be kept",default=10)
parser.add_argument('-o','--output-dir',metavar='<output dir>', type=str,help="output directory - defaults to working directory")
parser.add_argument('-t','--threads',metavar='<int>', type=int,help="number of cpus to use for pipeline - default of 4",default=4)

args = parser.parse_args()
